protected/models/Patient.php
<?php

/**
 * This is the model class for table "da_patient".
 *
 * The followings are the available columns in table 'da_patient':
 * @property integer $id
 * @property string $user_name
 * @property string $user_email
 * @property string $password
 * @property string $user_first_name
 * @property string $user_last_name
 * @property string $user_dob
 * @property string $user_sex
 * @property string $entry_type
 * @property string $visiter
 * @property string $patient_name
 * @property string $patient_email
 * @property string $patient_dob
 * @property integer $patient_sex
 * @property string $date_created
 * @property string $date_modified
 * @property integer $status
 */
class Patient extends CActiveRecord
{
	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return 'da_patient';
	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		return array(
			//array('user_name, user_email, password, user_first_name, user_last_name, user_dob, user_sex, entry_type, visiter, patient_name, patient_email, patient_dob, patient_sex, date_created, date_modified, status', 'required'),
			array('user_name, status', 'required'),
			array('status,force_pw_change', 'numerical', 'integerOnly'=>true),
			array('user_name,force_pw_change_resaon, user_email, password, user_first_name, user_last_name, patient_name, patient_email', 'length', 'max'=>32),
			array('user_sex', 'length', 'max'=>10),
			array('entry_type, visitor', 'length', 'max'=>5),
			array('user_first_name,user_last_name, user_phone, user_address, user_city, user_state, user_zip, user_contact_method', 'required', 'on'=>'edit_profile'),
			// The following rule is used by search().
			// @todo Please remove those attributes that should not be searched.
			array('id, user_name, user_email, password,force_pw_change_resaon, user_first_name, user_last_name, user_dob, user_sex, entry_type, visiter, patient_name, patient_email, patient_dob, patient_sex, date_created, date_modified, status', 'safe', 'on'=>'search'),
		);
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		// NOTE: you may need to adjust the relation name and the related
		// class name for the relations automatically generated below.
		return array(
		);
	}

	/**
	 * @return array customized attribute labels (name=>label) 
	 */
	public function attributeLabels()
	{
		return array(
			'id' => 'ID',
			'user_name' => 'User Name',
			'user_email' => 'User Email',
			'password' => 'Password',
			'user_first_name' => 'First Name',
			'user_last_name' => 'Last Name',
			'user_dob' => 'Date of Birth',
			'user_sex' => 'Sex',
			'user_phone' => 'Phone Number',
			'user_address' => 'Address',
			'user_city' => 'City',
			'user_state' => 'State',
			'user_zip' => 'Zip',
			'user_contact_method' => 'Preferred Contact Method',
			'entry_type' => 'Entry Type',
			'visiter' => 'Visiter',
			'patient_name' => 'Patient Name',
			'patient_email' => 'Patient Email',
			'patient_dob' => 'Patient Dob',
			'patient_sex' => 'Patient Sex',
			'date_created' => 'Date Created',
			'date_modified' => 'Date Modified',
			'status' => 'Status',
            'force_pw_change'=>'Force PW change',
            'force_pw_change_resaon'=>'Force PW change Reason'
		);
	}

	/**
	 * Retrieves a list of models based on the current search/filter conditions.
	 *
	 * Typical usecase:
	 * - Initialize the model fields with values from filter form.
	 * - Execute this method to get CActiveDataProvider instance which will filter
	 * models according to data in model fields.
	 * - Pass data provider to CGridView, CListView or any similar widget.
	 *
	 * @return CActiveDataProvider the data provider that can return the models
	 * based on the search/filter conditions.
	 */
	public function search()
	{
		// @todo Please modify the following code to remove attributes that should not be searched.

		$criteria=new CDbCriteria;

		$criteria->compare('id',$this->id);
		$criteria->compare('user_name',$this->user_name,true);
		$criteria->compare('user_email',$this->user_email,true);
		$criteria->compare('password',$this->password,true);
		$criteria->compare('user_first_name',$this->user_first_name,true);
		$criteria->compare('user_last_name',$this->user_last_name,true);
		$criteria->compare('user_dob',$this->user_dob,true);
		$criteria->compare('user_sex',$this->user_sex,true);
		$criteria->compare('entry_type',$this->entry_type,true);
		$criteria->compare('visiter',$this->visiter,true);
		$criteria->compare('patient_name',$this->patient_name,true);
		$criteria->compare('patient_email',$this->patient_email,true);
		$criteria->compare('patient_dob',$this->patient_dob,true);
		$criteria->compare('patient_sex',$this->patient_sex);
		$criteria->compare('date_created',$this->date_created,true);
		$criteria->compare('date_modified',$this->date_modified,true);
		$criteria->compare('status',$this->status);
		$criteria->compare('force_pw_change',$this->force_pw_change);
		$criteria->compare('force_pw_change_resaon',$this->force_pw_change_resaon);

		return new CActiveDataProvider($this, array(
			'criteria'=>$criteria,
		));
	}

	/**
	 * Returns the static model of the specified AR class.
	 * Please note that you should have this exact method in all your CActiveRecord descendants!
	 * @param string $className active record class name.
	 * @return Patient the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}
	
	public function getGenderOptions(){
		return array('male' => 'Male', 'female' => 'Female');
	}

	public function getContactMethod(){
		return array('Email' => 'Email', 'Phone' => 'Phone', 'Sms' => 'Sms');
	}

	public function getMonthOptions(){
		return array('01' => 'January', '02' => 'February', '03' => 'March', '94' => 'April', '05' => 'May', '06' => 'June', '07' => 'July', '08' => 'August', '09' => 'September', '10' => 'October', '11' => 'November', '12' => 'December');
	}
	
	public function getDateOptions(){
		return array('01' => '01', '02' => '02', '03' => '03', '04' => '04', '05' => '05', '06' => '06', '07' => '07', '08' => '08', '09' => '09', '10' => '10', '11' => '12', '13' => '13', '14' => '14', '15' => '15', '16' => '16', '17' => '17', '18' => '18', '19' => '19', '20' => '20', '21' => '21', '22' => '23', '24' => '24', '25' => '25', '26' => '26', '27' => '27', '28' => '28', '29' => '29', '30' => '30', '31' => '31');
	}
}

protected/controllers/PatientController.php
<?php

class PatientController extends Controller
{
	/*public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
			'postOnly + delete', // we only allow deletion via POST request
		);
	}
	public function accessRules()
	{
		return array(
			array('allow',  // allow all users to perform 'index' and 'view' actions
				'actions'=>array('index','view', 'create'),
				'users'=>array('*'),
			),
			array('allow', // allow authenticated user to perform 'create' and 'update' actions
				'actions'=>array('update'),
				'users'=>array('@'),
			),
			array('allow', // allow admin user to perform 'admin' and 'delete' actions
				'actions'=>array('admin','delete'),
				'users'=>array('admin'),
			),
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}*/
	
	public function actionIndex()
	{
		/*$dataProvider=new CActiveDataProvider('Doctor');
		$this->render('index',array(
			'dataProvider'=>$dataProvider,
		));*/
		if(Yii::app()->session['logged_in']){
			$model = new Patient();
			//print_r($_REQUEST);
			$model->id = Yii::app()->session['logged_user_id'];
			//$model->password = Yii::app()->getRequest()->getPost('password');
			$usercriteria =Patient::model()->find("id=\"$model->id\"");
		}else{
			$this->redirect(array('site/index'));
		}
		
		$name= Yii::app()->request->getParam('doctor_name');
		$start_date = Yii::app()->request->getParam('start_date');
		$end_date = Yii::app()->request->getParam('end_date');
		$status = Yii::app()->request->getParam('status');
		if($status != ""){
			if($status == "Accepted")	$status_confirm=1;
			if($status == "Pending")	$status_confirm=0;
			if($status == "Cancel")	$status_confirm=2;
			if($status == "Complete")	$status_confirm=3;
		}
		
		$sql_count='select db.*,dp.user_first_name as dp_name,da.address as da_address,da.city as da_city,da.zip as da_zip, dpro.procedure as dpro_procedure,d.title as d_title,d.id as d_id,d.gender as d_gender,d.image as d_image,concat_ws(" ", d.first_name,  d.last_name ) as d_doctor_name FROM da_doctor_book as db left join da_patient as dp on db.patient_id = dp.id  left join da_doctor as d on d.id = db.doctor_id left join da_doctor_address as da on db.address_id = da.id left join da_procedure as dpro on db.procedure_id = dpro.id WHERE db.status=1 and db.patient_id='.$model->id.' ';
		$sql_doctor_address='select db.*,dp.user_first_name as dp_name,da.address as da_address,da.city as da_city,da.zip as da_zip,dpro.procedure as dpro_procedure,d.title as d_title,d.id as d_id,d.gender as d_gender,d.image as d_image,concat_ws(" ", d.first_name,  d.last_name ) as d_doctor_name FROM da_doctor_book as db left join da_patient as dp on db.patient_id = dp.id  left join da_doctor as d on d.id = db.doctor_id left join da_doctor_address as da on db.address_id = da.id left join da_procedure as dpro on db.procedure_id = dpro.id WHERE db.status=1 and db.patient_id='.$model->id.' ';
		
		$input_name = preg_replace("/[^a-zA-Z]+/", "", $name);
		if($name != ""){
			$sql_count .= " and concat_ws( d.first_name, ' ', d.last_name )   like '%".$input_name."%' ";
			$sql_doctor_address .= " and concat_ws( d.first_name, ' ', d.last_name )   like '%".$input_name."%' ";
		}
		if($start_date != ""){
			$sql_count .= " and db.book_time >= '".strtotime($start_date)."' ";
			$sql_doctor_address .= " and db.book_time >= '".strtotime($start_date)."' ";
		}
		if($end_date != ""){
			$sql_count .= " and db.book_time <= '".strtotime($end_date)."' ";
			$sql_doctor_address .= " and db.book_time <= '".(strtotime($end_date)+(24*60*60))."' ";
		}
		if($status != "" && $status != "All"){
			$sql_count .= " and db.confirm = ".$status_confirm;
			$sql_doctor_address .= " and db.confirm = ".$status_confirm;
		}
		
		$sql_count .= " order by db.book_time desc ";
		$sql_doctor_address .= " order by db.book_time desc ";
		
		$limit = 10;
		$end_limit = 10;
		if(isset($_REQUEST['page']) && $_REQUEST['page']>1){
			$star_limit = ($limit*($_REQUEST['page']-1));
		}else{
			$star_limit = 0;
		}
		$sql_doctor_address .= ' limit '.$star_limit.','.$end_limit;
		$sql_count .= ' ';
		//echo $sql_doctor_address;
		
		$connection = Yii::app()->db;
		$command_doctor_address = $connection->createCommand($sql_doctor_address);
		$user_patient_book = $command_doctor_address->queryAll();
		
		$command_count = $connection->createCommand($sql_count);
		$doctor_list_count = $command_count->queryAll();
		$count=count($doctor_list_count);
		$pages=new CPagination($count);
		$criteria = new CDbCriteria(array(
			//'condition' => $condition,
        	//'order' => 'category_id DESC'
		));
	
		// results per page
		$pages->pageSize=$limit;
		$pages->applyLimit($criteria);
		
		//Helpers::pre($user_patient_book);die;
		$sql_speciality='select * FROM da_speciality WHERE status="1"';
		$command_speciality = $connection->createCommand($sql_speciality);
		$user_speciality = $command_speciality->queryAll();
		$user_speciality_res = array();
		foreach ($user_speciality as $key=>$val) {
			$user_speciality_res[$val['id']] = $val['speciality'];
		}
		$sql_procedure='select * FROM da_procedure WHERE status="1"';
		$command_procedure = $connection->createCommand($sql_procedure);
		$user_procedure = $command_procedure->queryAll();
		$user_procedure_res = array();
		foreach ($user_procedure as $key=>$val) {
			$user_procedure_res[$val['id']] = $val['procedure'];
		}
		
		$sql_reason_for_visit='select * FROM da_reason_for_visit WHERE status="1"';
		$command_reason_for_visit = $connection->createCommand($sql_reason_for_visit);
		$user_reason_for_visit = $command_reason_for_visit->queryAll();
		$user_reason_for_visit_res = array();
		foreach ($user_reason_for_visit as $key=>$val) {
			$user_reason_for_visit_res[$val['id']] = $val['reason_for_visit'];
		}
		
		$this->render('index',array(
			'dataProvider'=>$usercriteria,'user_patient_book' => $user_patient_book,'user_procedure' => $user_procedure_res,'user_speciality' => $user_speciality_res,'pages'=>$pages,'user_reason_for_visit' => $user_reason_for_visit_res,
		));
	}
	
	public function actionEditProfile($id = "")
	{
		if(!Yii::app()->session['logged_in'])
			$this->redirect(array('site/index'));
		$model = new stdClass();
		$model->id = Yii::app()->session['logged_user_id'];
		
		$model = Patient::model()->findByPk($model->id);
		$model->scenario = 'edit_profile';
		if($model->user_dob == "" || $model->user_dob == '0000-00-00'){
			$birth_date['mm'] = "";
			$birth_date['dd'] = "";
			$birth_date['yy'] = "";
		}else{
			$birth_date_arr =explode("-",$model->user_dob);
			$birth_date['mm'] = $birth_date_arr[1];
			$birth_date['dd'] = $birth_date_arr[2];
			$birth_date['yy'] = $birth_date_arr[0];
		}
		
		$start_year = date('Y')-70;
		//$end_year = date('Y')-20;
		$end_year = date('Y');
		$yearOptions = array();
		$count_year = $start_year;
		for($i=0;$i<=($end_year-$start_year);$i++){
			$yearOptions[$count_year]=$count_year;
			$count_year++;
		}
		if(Yii::app()->getRequest()->isPostRequest){
			$model->attributes=Yii::app()->getRequest()->getPost('Patient');
			$model->user_sex=Yii::app()->getRequest()->getPost('user_sex');
			$model->user_contact_method=Yii::app()->getRequest()->getPost('user_contact_method');
			$model->user_dob=$_REQUEST['yy']."-".$_REQUEST['mm']."-".$_REQUEST['dd'];
			if($model->save()){
				Yii::app()->user->setFlash('editProfile','Your profile has been updated.');
				$this->refresh();
			}
		}
		$this->render('edit_profile',array(
			'model' => $model,'birth_date' => $birth_date,'yearOptions' => $yearOptions,
		));
	}
	
	public function actionPatientReview() {
		if( !isset($_REQUEST['overall_rating']) ) {
			$this->redirect(array('404error'));
		}
		$overall_rating = $_REQUEST['overall_rating'];
		$bedside_manner_rating = $_REQUEST['bedside_manner_rating'];
		$wait_time_rating = $_REQUEST['wait_time_rating'];
		$scheduling_appointment=$_REQUEST['scheduling_appointment'];
		$office_experience=$_REQUEST['office_experience'];
		$spent_time=$_REQUEST['spent_time'];
		
		//$review_title = $_REQUEST['review_title'];
		$review_message = $_REQUEST['review_message'];
		$patient_id = Yii::app()->session['logged_user_id'];
		$doctor_id = $_REQUEST['doctor_id'];
		$status = 1;
		
		$sql='INSERT INTO da_doctor_review (doctor_id, patient_id, overall_rating, bedside_manner_rating, wait_time_rating,schedul_appoitment_rating,office_experience_rating,spent_time_rating , message, date_created, status) VALUES(:doctor_id,:patient_id,:overall_rating,:bedside_manner_rating,:wait_time_rating,:schedul_appoitment,
		:office_experience,:spent_time,:message,:date_created,:status)';
		$params = array(
			"doctor_id" => $doctor_id,
			"patient_id" => $patient_id,
			"overall_rating" => $overall_rating,
			"bedside_manner_rating" => $bedside_manner_rating,
			"wait_time_rating" => $wait_time_rating,
			"schedul_appoitment"=>$scheduling_appointment, 
			"office_experience"=>$office_experience, 
			"spent_time"=> $spent_time,
			/*"title" => $review_title,*/
			"message" => $review_message,
			"date_created" => date('Y-m-d h:i:s'),
			"status" => $status
		);
		$connection = Yii::app()->db;
		$command=$connection->createCommand($sql);
		$command->execute($params);
    }
	
	public function actionResetpassword()
	{
		if(!Yii::app()->session['logged_in']){
			$this->redirect(array('site/index'));
		}
		$error = array();
		if($_POST){
			
			$old_password = trim($_POST['old_password']);
			$new_password = $_POST['new_password'];
			$confirm_password = $_POST['confirm_password'];
			$connection = Yii::app()->db;
			$sql="select * FROM da_patient WHERE status=1 and id=".Yii::app()->session['logged_user_id']." and password='".md5($old_password)."'";
			$command = $connection->createCommand($sql);
			$user_arr = $command->queryAll();
			if(empty($user_arr)) $error['old_password'] = 'Password not matched.';
			if($new_password == '') $error['new_password'] = 'Password cannot be blank.';

protected/views/patient/reset_password.php
<?php
$this->breadcrumbs=array(
	'Reset Password',
);
?>
<div class="main">
    <div id="breadcrumb" class="fk-lbreadbcrumb newvd">
        <!--<span><a href="">Home</a></span> >  
        <span>Dashboard</span>--> 
        <?php $this->widget('zii.widgets.CBreadcrumbs', array(
				  'links'=>$this->breadcrumbs,
			  ));
		?>
    </div>
  	  <div class="dashboard_mainarea">
     	<div class="leftmenu" id="left_id">
     		<?php /*
       		 <h2>Patient control panel</h2>
             <ul>
            	 <li><?php echo CHtml::link('Dashboard', $this->createAbsoluteUrl('index')); ?></li>
                 <li><?php echo CHtml::link('My Account', $this->createAbsoluteUrl('patient/editProfile/'.Yii::app()->session['logged_user_id'])); ?></li>
                 <li class="active"><?php echo CHtml::link('Reset Password', $this->createAbsoluteUrl('doctor/resetpassword/'.Yii::app()->session['logged_user_id'])); ?></li>
             </ul>
             */ ?>
             <?php $this->renderPartial('//layouts/navigation'); ?>
        </div>
    
    <div class="rightarea_dashboard">
		<?php $form=$this->beginWidget('CActiveForm', array(
            'id'=>'reset_password',
        )); ?>
            <div class="dashboardcont_leftbox">
                <?php if(Yii::app()->user->hasFlash('resetPassword')): ?>
                    <span class="flash-success">
                        <?php echo Yii::app()->user->getFlash('resetPassword'); ?>
                    </span>
                <?php endif; ?>
                 <h1>Reset Password</h1>
                 <div class="box_content">
                    <div class="fld_area">
                       <div class="fld_name">Old Password</div>
                       <div class="name_fld">
                       <input id="old_password" class="fld_class" type="password" name="old_password" placeholder="Old Password" autocomplete="off" size="32" value="<?php if(isset($_REQUEST['old_password'])) echo $_REQUEST['old_password']; ?>">
                       <div class="errorMessage"><?php if(isset($error['old_password'])) echo $error['old_password']; ?></div>
                       </div>
                       <div class="clear"></div>             
                    </div>
                    <div class="fld_area custom-popup">
                       <div class="fld_name fld_name_hight">New Password</div>
                       <div class="name_fld">
                       <span class='rulepassword'>
                       <input id="new_password" class="fld_class" type="password" name="new_password" placeholder="New Password" autocomplete="off" size="32" value="<?php if(isset($_REQUEST['new_password'])) echo $_REQUEST['new_password']; ?>">
                       <div class="errorMessage"><?php if(isset($error['new_password'])) echo $error['new_password']; ?></div>
                            
                    </span>
                       
                      
                       </div>
                      
                       <div id="pswd_info">
                        <h4>Password must meet the following requirements:</h4>
                        <ul>
                         <li id="letter" class="invalid">At least <strong>one letter</strong></li>
                         <li id="capital" class="invalid">At least <strong>one capital letter</strong></li>
                         <li id="number" class="invalid">At least <strong>one number</strong></li>
                         <li id="length" class="invalid">Be at least <strong>8 characters</strong></li>
                        </ul>
                       </div>
                       <div class="clear"></div>
                    </div>
                    <div class="fld_area">
                       <div class="fld_name fld_name_hight">Confirm Password</div>
                       <div class="name_fld">
                       <input id="confirm_password" class="fld_class" type="password" name="confirm_password" placeholder="Confirm Password" autocomplete="off" size="32" value="<?php if(isset($_REQUEST['confirm_password'])) echo $_REQUEST['confirm_password']; ?>">
                       <div class="errorMessage"><?php if(isset($error['confirm_password'])) echo $error['confirm_password']; ?></div>
                       </div>
                       <div class="clear"></div>
                    </div>
                    
                </div>
            </div>
            <div>
                <span>
                <?php echo CHtml::submitButton('Update',array('class'=>'registbt')); ?>
                <?php echo CHtml::link('Cancel', $this->createAbsoluteUrl('patient/index'),array('class'=>'registbt')); ?>
                </span>
            </div>
        <?php $this->endWidget(); ?>
    </div>
     
  </div>
</div>

<script>
$(document).ready(function() {
$('input[type=submit]').attr('disabled',true).addClass('disSubBtnCls');
//you have to use keyup, because keydown will not catch the currently entered value
$('#new_password').keyup(function() {
 // set password variable
 var pswd = $(this).val();
 var lengthValid = 0;
 var letterValid = 0;
 var uppercaseValid = 0;
 var numberValid = 0;
 
 //validate the length
 if ( pswd.length < 8 ) {
  $('#length').removeClass('valid').addClass('invalid');
  lengthValid = 0;
 } else {
  $('#length').removeClass('invalid').addClass('valid');
  lengthValid = 1;
 }
 
 //validate letter
 if ( pswd.match(/[A-z]/) ) {
  $('#letter').removeClass('invalid').addClass('valid');
  letterValid = 1;
 } else {
  $('#letter').removeClass('valid').addClass('invalid');
  letterValid = 0;
 }
 
 //validate uppercase letter
 if ( pswd.match(/[A-Z]/) ) {
  $('#capital').removeClass('invalid').addClass('valid');
  uppercaseValid = 1;
 } else {
  $('#capital').removeClass('valid').addClass('invalid');
  uppercaseValid = 0;
 }
 
 //validate number
 if ( pswd.match(/\d/) ) {
  $('#number').removeClass('invalid').addClass('valid');
  numberValid = 1;
 } else {
  $('#number').removeClass('valid').addClass('invalid');
  numberValid = 0;
 }
 
 if(lengthValid == 1 && letterValid == 1 && uppercaseValid == 1 && numberValid == 1)
 {
  /*$("#btn1").show();
  $("#btn2").hide();*/
  $('input[type=submit]').attr('disabled',false).removeClass('disSubBtnCls');
  setTimeout(function(){$('#pswd_info').hide();},800);      
 }
 else
 {
  $('#pswd_info').show();
  /*$("#btn1").hide();
  $("#btn2").show();*/
  $('input[type=submit]').attr('disabled',true).addClass('disSubBtnCls');
 }
 
}).focus(function() {
 $('#pswd_info').show();
 if($('#new_password').val() == '')
 {
  /*$("#btn1").hide();
  $("#btn2").show();*/
 }     
}).blur(function() {
 $('#pswd_info').hide();
});
});
</script>