protected/models/Documents.php
<?php

/**
 * This is the model class for table "db_document".
 *
 * The followings are the available columns in table 'db_document':
 * @property integer $id
 * @property string $owner
 * @property string $document_name
 * @property string $label
 * @property string $status
 * @property string $date
 * @property string $note
 * @property string $file_url
 * @property string $is_private
 * @property string $is_share
 * @property string $key
 */
class Documents extends CActiveRecord
{
	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return 'db_document';
	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		return array(
			array('document_name, label, note,date,patient_name','required'),
			array('owner', 'length', 'max'=>500),
			array('document_name', 'length', 'max'=>1000),
			array('label', 'length', 'max'=>100),
			array('note', 'length', 'max'=>2000),
			array('key', 'length', 'max'=>200),
			// The following rule is used by search().
			// @todo Please remove those attributes that should not be searched.
			array('id, owner, document_name, label, status, date, note, is_private,owner_type, is_share, key,patient_name', 'safe', 'on'=>'search'),
			array('owner,date,patient_name,patient_id,owner_type,status', 'safe'),
		);
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		// NOTE: you may need to adjust the relation name and the related
		// class name for the relations automatically generated below.
		return array(
            'docFiles' => array(self::HAS_MANY, 'DocumentFiles', 'document_id'),
		);
	}

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'id' => 'ID',
			'owner' => 'Owner',
			'document_name' => 'Document Name',
			'label' => 'Label',
			'status' => 'Status',
			'date' => 'Date',
			'note' => 'Note',
			'is_private' => 'Is Private',
			'is_share' => 'Is Share',
			'key' => 'Key',
		);
	}

	/**
	 * Retrieves a list of models based on the current search/filter conditions.
	 *
	 * Typical usecase:
	 * - Initialize the model fields with values from filter form.
	 * - Execute this method to get CActiveDataProvider instance which will filter
	 * models according to data in model fields.
	 * - Pass data provider to CGridView, CListView or any similar widget.
	 *
	 * @return CActiveDataProvider the data provider that can return the models
	 * based on the search/filter conditions.
	 */
	public function search()
	{
		// @todo Please modify the following code to remove attributes that should not be searched.

		$criteria=new CDbCriteria;

		$criteria->compare('id',$this->id);
		$criteria->compare('owner',$this->owner,true);
		$criteria->compare('document_name',$this->document_name,true);
		$criteria->compare('label',$this->label,true);
		$criteria->compare('status',$this->status,true);
		$criteria->compare('date',$this->date,true);
		$criteria->compare('note',$this->note,true);
		$criteria->compare('file_url',$this->file_url,true);
		$criteria->compare('is_private',$this->is_private,true);
		$criteria->compare('is_share',$this->is_share,true);
		$criteria->compare('key',$this->key,true);

		return new CActiveDataProvider($this, array(
			'criteria'=>$criteria,
		));
	}

	/**
	 * Returns the static model of the specified AR class.
	 * Please note that you should have this exact method in all your CActiveRecord descendants!
	 * @param string $className active record class name.
	 * @return Documents the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}
    public function beforeSave(){


        if ($this->isNewRecord){
            $this->owner = Yii::app()->session['logged_user_id'];
            $this->created_date = date('Y-m-d H:m:s');
            $this->updated_date = date('Y-m-d H:m:s');
        }else{
            $this->updated_date = date('Y-m-d H:m:s');
        }

        return true;
    }
}

protected/controllers/DocumentsController.php
<?php
class DocumentsController extends Controller
{
    /**
     * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
     * using two-column layout. See 'protected/views/layouts/column2.php'.
     */
    public $layout = '//layouts/column2';

    /**
     * @return array action filters
     */
    public function filters()
    {
        return array(
            'accessControl', // perform access control for CRUD operations
            'postOnly + delete', // we only allow deletion via POST request
        );
    }

    /**
     * Specifies the access control rules.
     * This method is used by the 'accessControl' filter.
     * @return array access control rules
     */
    public function accessRules()
    {
        return array(
            array('allow', // allow all users to perform 'index' and 'view' actions
                'actions' => array('index', 'view', 'compose', 'download','link', 'search','list', 'document', 'update','getLists'),
                'users' => array('*'),
            ),
            array('allow', // allow authenticated user to perform 'create' and 'update' actions
                'actions' => array('create', 'update'),
                'users' => array('@'),
            ),
            array('allow', // allow admin user to perform 'admin' and 'delete' actions
                'actions' => array('admin', 'delete'),
                'users' => array('admin'),
            ),
            array('deny', // deny all users
                'users' => array('*'),
            ),
        );
    }

    /**
     * Displays a particular model.
     * @param integer $id the ID of the model to be displayed
     */
    public function actionView($id)
    {


        $this->render('view', array(
            'model' => $this->loadModel($id),
        ));
    }

    /**
     * Creates a new model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     */
    public function actionCreate()
    {
        $model = new Documents;

        // Uncomment the following line if AJAX validation is needed
        // $this->performAjaxValidation($model);

        if (isset($_POST['Documents'])) {
            $model->attributes = $_POST['Documents'];
            if ($model->save())
                $this->redirect(array('view', 'id' => $model->id));
        }

        $this->render('create', array(
            'model' => $model,
        ));
    }

    /**
     * Updates a particular model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id the ID of the model to be updated
     */

    public function actionComposer()
    {
        $model = new Documents();



        if (isset($_POST)) {
            if(Yii::app()->session['logged_user_type'] == "patient" ){
                $model->owner_type="p";
            }
            if(Yii::app()->session['logged_user_type'] == "doctor"||Yii::app()->session['logged_user_type'] == "parcticeAdmin" ){
                $model->owner_type="d";
                $model->status="shared";
            }
            if(!isset($_POST['patient_id'])){
                $model->patient_id= Yii::app()->session['logged_user_id'];
                $user = Patient::model()->findByPk(Yii::app()->session['logged_user_id']);
                $model->patient_name= $user->user_first_name;
            }

            $model->attributes = $_POST;

            $savemodel=false;
            if (isset($_FILES['image'])) {
                foreach ($_FILES['image']['name'] as $key => $name) {
                    if ($name != '') {
                        if (!defined('awsAccessKey')) define('awsAccessKey', Yii::app()->params['awsAccessKey']);
                        if (!defined('awsSecretKey')) define('awsSecretKey', Yii::app()->params['awsSecretKey']);
                        //$s3 = new S3(awsAccessKey, awsSecretKey);
                        S3::setAuth(Yii::app()->params['awsAccessKey'], Yii::app()->params['awsSecretKey']);
                        S3::$endpoint=Yii::app()->params['awsEndPoint'];
                        $doc_file = new DocumentFiles();
                        $fileName = $_FILES['image']['name'][$key];
                        $fileTempName = $_FILES['image']['tmp_name'][$key];
                        $exts = explode('.', $fileName);
                        $names=current($exts);
                        $ext = end($exts);
                        $fileName = $names."_".uniqid() . '.' . $ext;

                        ///////encryption works from here ....
                        $securityManager = new CSecurityManager;
                        $securityManager->setEncryptionKey(Yii::app()->params['fileEncryptKey']);
                       // $fileData = file_get_contents($_FILES["image"]["tmp_name"][$key]);
                        $fileData = $securityManager->encrypt(base64_encode(file_get_contents($_FILES["image"]["tmp_name"][$key])));
                        $pathNew = Yii::app()->basePath.'/../images/uploads/';
                        file_put_contents($pathNew.$fileName,$fileData);
                        /////uploads to s3 bucket........
                        if (S3::putObject(S3::inputFile($pathNew.$fileName),Yii::app()->params['awsBucket'],$fileName,S3::ACL_PRIVATE,array(),$_FILES['image']['type'][$key],S3::STORAGE_CLASS_STANDARD,S3::SSE_AES256)) {
                            $furl =  $fileName;
                            $savemodel = $model->save();
                            $doc_file->document_id = $model->id;
                            $doc_file->file_url = $furl;
                            $doc_file->save();
                        }
                    }

                }
            }
            if ($savemodel) {

                $log = new Log ;
                $log->user_id = Yii::app()->session['logged_user_id'];
                $log->user_type = Yii::app()->session['logged_user_type'];
                $log->controller = $this->getId();
                $log->action = $this->getAction()->getId();
                $log->created_at = time();
                $log->request =Yii::app()->request->requestUri ;
                $log->param = $model->id;
                $log->save();

                return $model = 1;

            }
        }

       return $model->errors;
    }


    public function actionCompose()
    {
        $model = $this->actionComposer();
        if ($model==1) {
            echo 1;
        } else {
            echo 0;
        }
    }

    public function actionDocument()
    {
        $model = $this->actionComposer();
        if ($model) {
            echo json_encode($model->attributes);
        } else {
            echo 0;
        }
    }
    public function accessCheck(){

        if (isset(Yii::app()->session['logged_user_type']) && (Yii::app()->session['logged_user_type'] == "doctor" ||Yii::app()->session['logged_user_type']=="parcticeAdmin")) {
            $user_type = 1;
            $owner_type = "d";
        } elseif ((Yii::app()->session['logged_user_type'] == "patient")) {
            $user_type = 0;
            $owner_type = "p";
        }
        $doc= Documents::model()->findByAttributes(array('owner'=>Yii::app()->session['logged_user_id'],'owner_type'=>$owner_type));
        if($doc){
            return true;
        }else{
            $shared=SharedDocument::model()->findByAttributes(array('shared_id'=>Yii::app()->session['logged_user_id'],'shared_type'=>$owner_type));
            if($shared){
                return true;
            }else{
                return false;
            }
        }

    }

    public function actionDownload($url)
    {
       // print_r($url);exit;
        $this->layout=false;
        if($this->accessCheck()){
            $url = DocumentFiles::model()->findByPk($url);
            $file = $url->file_url;

            S3::setAuth(Yii::app()->params['awsAccessKey'], Yii::app()->params['awsSecretKey']);
            //$result = $s3->getObject("nintrivatestapp",$file);
            $time = Yii::app()->params['time'];
            $bucket = Yii::app()->params['awsBucket'];
            S3::$endpoint=Yii::app()->params['awsEndPoint'];
            $obj = S3::getObject($bucket,$file);
            /*echo '<pre>';
            print_r($obj); exit;*/
           $signedUrl = S3::getAuthenticatedURL($bucket,$file,"+{$time} minutes",false,true);
          // print_r($signedUrl); exit;

            $securityManager = new CSecurityManager;
            $securityManager->setEncryptionKey(Yii::app()->params['fileEncryptKey']);
           //
           // print_r(file_get_contents($signedUrl)); exit;
           // $temp = (file_get_contents());
//
            $fileData =  base64_decode($securityManager->decrypt($obj->body));
           // $fileData = $securityManager->decrypt((file_get_contents($signedUrl)));
           /* print_r(Yii::app()->basePath) ; exit;*/
            $fileName = uniqid() . '_' . $file;
            $pathNew =Yii::app()->basePath.'/../images/uploads/'.$fileName;

            file_put_contents($pathNew,$fileData);

            //print_r($fileName); exit;


            $this->render('doc_view', array(
                'signedUrl' =>$fileName ,
            ));
        }else{

            throw new CHttpException(403, 'Access Denied');
        }


//        header('Location: '.$signedUrl);
    }

      public function actionLink($url)
      {
          if($this->accessCheck()){
              $url = DocumentFiles::model()->findByPk($url);
              $file = $url->file_url;
              //$file = explode('/', $url);
              $exts = explode('.', $file);
              $ext = end($exts);
              S3::setAuth(Yii::app()->params['awsAccessKey'], Yii::app()->params['awsSecretKey']);
              $bucket = Yii::app()->params['awsBucket'];
              $time = Yii::app()->params['time'];
              S3::$endpoint=Yii::app()->params['awsEndPoint'];

protected/views/documents/doc_view.php
<head>
    <script language="javascript">
        $(function() {
            $(this).bind("contextmenu", function(e) {
                e.preventDefault();
            });
        });
    </script>

</head>
<body oncontextmenu="return false">
<iframe name="myIframe" target="_blank" style="width: 100%;border: 0;height: 100%;" src="../images/uploads/<?php echo $signedUrl?>"></iframe>
</body>

protected/views/documents/update.php
<?php

$this->breadcrumbs=array(
    'Update Document',
);

?>
<div class="main">
    <div id="breadcrumb" class="fk-lbreadbcrumb newvd">
        <!--<span><a href="">Home</a></span> >
        <span>Dashboard</span>-->
        <?php $this->widget('zii.widgets.CBreadcrumbs', array(
            'links'=>$this->breadcrumbs,
        ));
        ?>
    </div>
    <div class="dashboard_mainarea">
        <div class="leftmenu" id="left_id">

            <?php $this->renderPartial('//layouts/navigation'); ?>
        </div>

        <div class="rightarea_dashboard">
            <?php $form=$this->beginWidget('CActiveForm', array(
                'id'=>'update_document',
            )); ?>
            <div class="dashboardcont_leftbox">
                <?php if(Yii::app()->user->hasFlash('update_document')): ?>
                    <span class="flash-success">
                        <?php echo Yii::app()->user->getFlash('update_document'); ?>
                    </span>
                <?php endif; ?>
                <h1>Update Document</h1>

                <div class="box_content">
                    <div class="fld_area">
                        <?php echo $form->labelEx($model,'document_name',array('class'=>'fld_name')); ?>
                        <div class="name_fld">
                            <?php echo $form->textField($model,'document_name',array('size'=>32,'maxlength'=>32,'placeholder'=> 'First Name','class'=>'fld_class')); ?>
                            <?php echo $form->error($model,'document_name'); ?>
                        </div>
                        <div class="clear"></div>
                    </div>
                    <div class="fld_area">

                        <?php echo $form->hiddenField($model,'label',array('id'=>'label_id')); ?>
                        <?php echo $form->labelEx($model,'label',array('class'=>'fld_name')); ?>
                        <div class="name_fld">
                            <?php if( isset(Yii::app()->session['logged_user_type']) && (Yii::app()->session['logged_user_type'] == "doctor"||Yii::app()->session['logged_user_type'] == "parcticeAdmin" ) ) {?>
                                <select name="label" id="label_name" style="border: 1px solid #A6AFAF;">
                                    <option>Select Label</option>
                                    <option>Advanced Directive</option>
                                    <option >Authorization</option>
                                    <option >Cardiopulmonary Diagnosis</option>
                                    <option >Clinical Summary</option>
                                    <option >Consent for Treatment</option>
                                    <option >Consultation</option>
                                    <option >CT Report</option>
                                    <option >Demographics</option>
                                    <option >Diagnostic Ultrasound</option>
                                    <option >Disability Info</option>
                                    <option >Discharge Summary</option>
                                    <option >Dismissals</option>
                                    <option >Drivers License</option>
                                    <option >ECHO</option>
                                    <option >EEG-EMG</option>
                                    <option >EKG</option>
                                    <option >Eligibility</option>
                                    <option>Emergency Department</option>
                                    <option>Explanation of Benefits</option>
                                    <option>History and Physical</option>
                                    <option>Hospital History</option>
                                    <option>Immunization History</option>
                                    <option>Imported Document</option>
                                    <option>Insurance Card</option>
                                    <option>Insurance Correspondence</option>
                                    <option>Insurance Referral</option>
                                    <option>Letter of Medical Necessity</option>
                                    <option>Mammography Document</option>
                                    <option>Medical Record Request</option>
                                    <option>Medical Report</option>
                                    <option>Misc. Doc</option>
                                    <option>Misc. Hospital Document</option>
                                    <option>Misc. Lab Result</option>
                                    <option>Missed Appointment</option>
                                    <option>Nursing Home Visit/Home Care</option>
                                    <option>OB Documentation</option>
                                    <option>OB Non-Stress Test</option>
                                    <option>Office Consult Note</option>
                                    <option>Office History and Physical</option>
                                    <option>Office Procedure Report</option>
                                    <option>Other</option>
                                    <option>Other Office Letter</option>
                                    <option>Other Office Note</option>
                                    <option>Pathology Report</option>
                                    <option>Patient Authorization/Referral</option>
                                    <option>Patient Correspondence</option>
                                    <option>Patient Demographics</option>
                                    <option>Patient Driver&#39;s License</option>
                                    <option>Patient Insurance Card</option>
                                    <option>Patient Letter</option>
                                    <option>Physician Established Patient Note</option>
                                    <option>Physician New Patient Note</option>
                                    <option>Prescriptions</option>
                                    <option>Radiology Diagnostic</option>
                                    <option>Radiology/Oncology</option>
                                    <option>Referral Letter</option>
                                    <option>Release of Information</option>
                                    <option>Request for Amendment</option>
                                    <option>Summary of Care Received</option>
                                    <option>Surgery/Procedure Report</option>
                                    <option>Tests</option>
                                    <option>Therapy Note</option>
                                    <option>Treadmill Report</option>
                                    <option>Ultrasound</option>
                                    <option>Ultrasound Document</option>
                                    <option>Urgent Care Visit Note</option>
                                </select>
                            <?php }?>
                            <?php if( isset(Yii::app()->session['logged_user_type']) && (Yii::app()->session['logged_user_type'] == "patient" ) ) {?>
                            <select name="label" id="label_name" style="border: 1px solid #A6AFAF;">
                                <option value="">Select Label</option>
                                <option value="Advanced Directive">Advanced Directive</option>
                                <option value="Authorization">Authorization</option>
                                <option>Consent for Treatment</option>
                                <option>Consultation</option>
                                <option>X-Ray</option>
                                <option>Demographics</option>
                                <option>Diagnostic Ultrasound</option>
                                <option>Disability Info</option>
                                <option>Drivers License</option>
                                <option>ECHO</option>
                                <option>EEG-EMG</option>
                                <option>EKG</option>
                                <option>Eligibility</option>
                                <option>History and Physical</option>
                                <option>Hospital History</option>
                                <option>Immunization History</option>
                                <option>Imported Document</option>
                                <option>Insurance Card</option>
                                <option>Insurance Correspondence</option>
                                <option>Letter of Medical Necessity</option>
                                <option>Mammography Document</option>
                                <option>Medical Record Request</option>
                                <option>Medical Report</option>
                                <option>Misc. Doc</option>
                                <option>Other</option>
                                <option>Pathology Report</option>
                                <option>Prescriptions</option>
                                <option>Release of Information</option>
                                <option>Request for Amendment</option>
                                <option>Summary of Care Received</option>
                                <option>Surgery/Procedure Report</option>
                                <option>Tests</option>
                                <option>Therapy Note</option>
                                <option>Treadmill Report</option>
                                <option>Ultrasound Document</option>
                                <option>Urgent Care Visit Note</option>
                            </select>
                        </div>
                    <?php }?>
                        </div>
                        <div class="clear"></div>
                    </div>
                    <div class="fld_area">
                        <?php echo $form->labelEx($model,'status',array('class'=>'fld_name')); ?>
                        <?php echo $form->hiddenField($model,'status',array('id'=>'status')); ?>
                        <div class="name_fld">
                            <select  id="status_name" name="status" style="border: 1px solid #A6AFAF;">
                                <option value="private">Private</option>
                                <option value="shared">Shared</option>
                            </select>
                        </div>
                        <div class="clear"></div>
                    </div>
                    <div class="fld_area">
                        <?php echo $form->labelEx($model,'note',array('class'=>'fld_name')); ?>
                        <div class="name_fld">
                            <?php echo $form->textArea($model,'note',array('style'=>'margin: 0px 4.734375px 0px 0px;
    height: 96px','placeholder'=> 'First Name','class'=>'fld_class')); ?>
                            <?php echo $form->error($model,'note'); ?>
                        </div>
                        <div class="clear"></div>
                    </div>
                <?php if(isset($model->docFiles) && $model->docFiles){?>
                <div class="fld_area">
                    <?php echo $form->labelEx($model,'attached_files',array('class'=>'fld_name','style'=>'margin-top:10px')); ?>

                    <div class="name_fld">

                     <?php
                    foreach($model->docFiles as $files){

                    $file =  $files->file_url;
                    ?>
                    <div class="massege_title">
                        <span class="sender_label"><?php echo $file ?></span>
                        <!--<span class="sender_body">  <a style="float: left" href="<?php /*echo Yii::app()->createUrl('documents/remove', array('url' =>$files->file_url));*/?>">
                                remove&nbsp;&nbsp;
                            </a></span>-->
                    </div>
                <?php   }?>
                    </div>
            </div>
                <?php }?>

                </div>

            </div>

            <div>
                <span style="margin-left: 300px;">
               <?php echo CHtml::submitButton('Update',array( 'class' => 'registbt'));
                   if (Yii::app()->session['logged_user_type'] == "doctor"||Yii::app()->session['logged_user_type'] == "parcticeAdmin"){
               echo CHtml::link('Cancel',array('doctor/document'),array('type'=>'button','style'=>'font-size:12px','class'=>'registbt')); }
               else if(Yii::app()->session['logged_user_type'] == "patient"){
                    echo CHtml::link('Cancel',array('patient/document'),array('type'=>'button','style'=>'font-size:12px','class'=>'registbt')); }?>

                </span>
            </div>

            <?php $this->endWidget(); ?>
        </div>

    </div>
</div>

<script>
    var label = $('#label_id').val();
    $('#label_name').val(label);

    var status = $('#status').val();
    $('#status_name').val(status);

</script>

protected/views/documents/view.php
<?php

$this->breadcrumbs=array(
    'Documents'=>array('view'),
    'Document Details',
);
?>
<div class="main">
    <div id="breadcrumb" class="fk-lbreadbcrumb newvd">
        <!--<span><a href="">Home</a></span> >
        <span>Dashboard</span>-->
        <?php $this->widget('zii.widgets.CBreadcrumbs', array(
            'links'=>$this->breadcrumbs,
        ));
        ?>
    </div>
    <div class="dashboard_mainarea">
        <div class="leftmenu">
            <?php $this->renderPartial('//layouts/navigation'); ?>
        </div>
        <?php //echo "<pre>";print_r($inbox_arr_details); echo "<pre>";print_r($pgn); ?>
        <div class="rightarea_dashboard">
            <div class="dashboardcont_leftbox messg_details" >
                <h1><span>Document Detail</span></h1>
                <div class="massege_title" style="margin-top:10px;">
                    <span class="sender_label">Document Name :</span>
                    <span class="sender_body"><?php echo $model->document_name;?></span>
                </div>
                <div class="massege_title">
                    <span class="sender_label">Label :</span>
                    <span class="sender_body"><?php echo $model->label;?></span>
                </div>
                <div class="massege_title">
                    <span class="sender_label">Note :</span>
                    <span class="sender_body"><?php echo $model->note;?></span>
                </div>
                <div class="massege_title">
                    <span class="sender_label">Date :</span>
                    <span class="sender_body"><?php echo $model->date;?></span>
                </div>
                <?php if($model->docFiles) {
                    ?>
                    <div class="massege_title" style="margin-top: 10px">
                        <h2>Attached Files</h2>
                    </div>
                    <?php
                    foreach($model->docFiles as $files){

                        $file =  $files->file_url;
                        $file1 = explode('_', $file);
						$text = str_replace(end($file1), '', $file);
						$name = rtrim($text, "_")
						
                  ?>
                    <div class="massege_title">
                        <span class="sender_label" style="word-wrap:break-word;width: 32%"><?php echo $name;?></span>
                        <span class="sender_body">

                            <a target="_blank" style="float: left;margin-left: 235px;margin-top: -25px;" href="<?php echo Yii::app()->createUrl('documents/download', array('url' =>$files->id));?>">
                                View&nbsp;&nbsp;
                            </a>
                        <a style="float: left;     margin-top: -25px;" href="<?php echo Yii::app()->createUrl('documents/link', array('url' =>$files->id));?>">
                            Download&nbsp;&nbsp;
                        </a></span>
                    </div>


                <?php   }}?>
                <span class="massege_title">

                    <a class="mesg_rply_btn" href="<?php echo Yii::app()->createUrl('documents/update', array('id' =>$model->id));?>">Edit</a>
                    <?php if( isset(Yii::app()->session['logged_user_type']) && (Yii::app()->session['logged_user_type'] == "doctor"||Yii::app()->session['logged_user_type'] == "parcticeAdmin" ) ) {?>
                        <a class="mesg_rply_btn" href="<?php echo Yii::app()->createUrl('doctor/document');?>">Back</a>
      <?php }else{?>                      <a class="mesg_rply_btn" href="<?php echo Yii::app()->createUrl('patient/document');?>">Back</a>
                    <?php }?>
	            </span>

                </div>
        </div>
    </div>